import "./globals.css";
import type { Metadata } from "next";
import { Roboto_Flex, Open_Sans } from "next/font/google";

const roboto = Roboto_Flex({ subsets: ["latin"] });
const opensans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className + opensans.className}>{children}</body>
    </html>
  );
}
